"""Issue lanes: what an agent may pick up, touch and merge on its own."""

from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "plugins/common/workflow/skills/afk/scripts/lanes.py"
spec = importlib.util.spec_from_file_location("lanes", SCRIPT)
lanes = importlib.util.module_from_spec(spec)
spec.loader.exec_module(lanes)

OWNER = "acme"
TRACKED = ["src/stage/a.py", "src/justfile", "tests/stage/test_a.py", "tools/gate.py", "justfile",
           "infra/dns.tf", "docs/guide.md"]


def config(**overrides):
    with tempfile.TemporaryDirectory() as tmp:
        (Path(tmp) / ".github").mkdir()
        data = {"repo": f"{OWNER}/app", "protected": ["^infra/", "^tools/"],
                "alwaysInScope": ["docs/"], **overrides}
        (Path(tmp) / ".github/lanes.json").write_text(json.dumps(data))
        return lanes.load_config(tmp)


CONFIG = config()


def issue(number=1, labels=("lane:afk",), body=None, state="OPEN"):
    if body is None:
        body = ('### Acceptance criteria\n\n- It works.\n\n```scope\n'
                '{"paths": ["src/stage/", "tests/"], "dependencies": [7, "#8"]}\n```')
    return {"number": number, "title": "feat(stage): a thing", "body": body, "state": state,
            "labels": [{"name": n} for n in labels]}


def pr(files, author=OWNER, **overrides):
    return {"state": "OPEN", "isDraft": False, "baseRefName": "main",
            "headRepositoryOwner": {"login": OWNER}, "author": {"login": author},
            "files": [{"path": f, "changeType": "MODIFIED"} for f in files], **overrides}


def thread(path="src/a.py", line=3, body="Guard the empty list.\n\n_Generated by Host_", author="reviewer"):
    return {"path": path, "line": line, "body": body, "author": author}


class ConfigTests(unittest.TestCase):
    def test_lists_extend_defaults_and_scalars_replace_them(self) -> None:
        custom = config(base="trunk", chores=["^guide/"])
        self.assertEqual(custom["base"], "trunk")
        self.assertEqual(custom["owner"], OWNER)
        self.assertIn(r"^\.[^/]+/", custom["protected"])
        self.assertEqual(custom["branchPrefix"], "agent/afk-")
        self.assertIn("^infra/", custom["protected"])
        self.assertIn("^guide/", custom["chores"])
        self.assertIn(r"^docs/", custom["chores"])


class PacketTests(unittest.TestCase):
    def test_packet_reads_both_fences_and_dependency_styles(self) -> None:
        self.assertEqual(lanes.packet(issue()["body"])["dependencies"], [7, 8])
        legacy = lanes.packet('```factory\n{"paths": ["docs/"]}\n```')
        self.assertEqual(legacy, {"paths": ["docs/"], "dependencies": []})

    def test_paths_must_be_a_list_of_strings(self) -> None:
        self.assertIsNone(lanes.packet('```scope\n{"paths": "docs/"}\n```'))
        self.assertIsNone(lanes.packet('```scope\n{"paths": [1]}\n```'))

    def test_missing_or_broken_packet_is_none(self) -> None:
        self.assertIsNone(lanes.packet("no packet"))
        self.assertIsNone(lanes.packet('```scope\n{"paths": [}\n```'))

    def test_packet_may_not_reach_protected_paths(self) -> None:
        self.assertEqual(lanes.packet_violations(["tools/", ".github/x/"], TRACKED, CONFIG),
                         ["tools/", ".github/x/"])
        self.assertEqual(lanes.packet_violations(["../x", "a/*", "/etc/"], TRACKED, CONFIG),
                         ["../x", "a/*", "/etc/"])
        self.assertEqual(lanes.packet_violations(["src/stage/", "tests/", "docs/"], TRACKED, CONFIG), [])

    def test_a_subtree_holding_protected_files_is_refused(self) -> None:
        self.assertEqual(lanes.packet_violations(["src/"], TRACKED, CONFIG), ["src/"])


class EligibilityTests(unittest.TestCase):
    def test_owner_approved_issue_with_done_dependencies_is_eligible(self) -> None:
        self.assertIsNone(lanes.ineligible(issue(), {7, 8}, False, TRACKED, CONFIG))

    def test_each_gate_refuses_with_its_reason(self) -> None:
        cases = [
            (issue(labels=("lane:proposed",)), "not lane:afk"),
            (issue(labels=("lane:afk", "type:epic")), "epic"),
            (issue(labels=("lane:afk", "type:task")), "task"),
            (issue(labels=("lane:afk", "state:claimed")), "claimed"),
            (issue(labels=("lane:afk", "state:started")), "started in another session"),
            (issue(body='```scope\n{"paths": ["docs/"]}\n```'), "no acceptance criteria"),
            (issue(body="## Acceptance criteria\n- x"), "no scope packet"),
        ]
        for candidate, reason in cases:
            with self.subTest(reason=reason):
                self.assertEqual(lanes.ineligible(candidate, {7, 8}, False, TRACKED, CONFIG), reason)
        self.assertEqual(lanes.ineligible(issue(), {7}, False, TRACKED, CONFIG), "waiting on #8")
        self.assertEqual(lanes.ineligible(issue(), {7, 8}, True, TRACKED, CONFIG), "has an open PR")

    def test_queue_order_is_priority_then_age(self) -> None:
        issues = [issue(5, ("lane:afk", "priority:P2")), issue(9, ("lane:afk", "priority:P0")),
                  issue(3, ("lane:afk",)), issue(4, ("lane:afk", "priority:P0"))]
        self.assertEqual([i["number"] for i in sorted(issues, key=lanes.rank)], [4, 9, 5, 3])

    def test_the_board_priority_field_outranks_labels(self) -> None:
        issues = [issue(5, ("lane:afk", "priority:P0")), issue(9, ("lane:afk",)), issue(3, ("lane:afk",))]
        board = {5: "P2", 9: "P1", 3: None}
        self.assertEqual([i["number"] for i in sorted(issues, key=lambda i: lanes.rank(i, board))], [9, 5, 3])

    def test_board_priorities_read_this_repositorys_issues_only(self) -> None:
        repo = object.__new__(lanes.Repo)
        repo.config, repo.name = config(project={"owner": OWNER, "number": 3}), f"{OWNER}/app"
        items = {"items": [
            {"content": {"type": "Issue", "number": 4, "repository": f"{OWNER}/app"}, "priority": "P0"},
            {"content": {"type": "Issue", "number": 4, "repository": f"{OWNER}/other"}, "priority": "P2"},
            {"content": {"type": "PullRequest", "number": 6, "repository": f"{OWNER}/app"}, "priority": "P1"},
            {"content": {"type": "DraftIssue"}},
        ]}
        original, lanes.gh_json = lanes.gh_json, lambda *args: items
        try:
            self.assertEqual(repo.board_priorities(), {4: "P0"})
            repo.config = config()
            self.assertEqual(repo.board_priorities(), {})
        finally:
            lanes.gh_json = original


class ScopeTests(unittest.TestCase):
    def test_changes_stay_inside_the_packet_plus_always_in_scope(self) -> None:
        self.assertEqual(lanes.out_of_scope(["src/stage/b.py", "docs/guide.md"], ["src/stage/"], CONFIG), [])

    def test_other_and_protected_changes_are_reported(self) -> None:
        changed = ["src/kernel/x.py", "justfile", "AGENTS.md", "tools/gate.py", ".github/workflows/ci.yml"]
        self.assertEqual(lanes.out_of_scope(changed, ["src/"], CONFIG), changed[1:])


class AutomergeTests(unittest.TestCase):
    def test_docs_and_tests_from_the_owner_merge_on_green(self) -> None:
        files = ["docs/guide.md", "tests/stage/test_a.py", "packages/web/README.md"]
        self.assertIsNone(lanes.merge_refusal(pr(files), CONFIG))

    def test_project_chores_extend_the_defaults(self) -> None:
        self.assertIsNone(lanes.merge_refusal(pr(["guide/perform.mdx"]), config(chores=["^guide/"])))

    def test_dependency_files_merge_only_from_dependabot(self) -> None:
        files = ["web/package.json", "web/package-lock.json"]
        self.assertIsNone(lanes.merge_refusal(pr(files, author="app/dependabot"), CONFIG))
        self.assertIn("scope packet", lanes.merge_refusal(pr(files), CONFIG))

    def test_dependabot_major_versions_wait_for_the_owner(self) -> None:
        files = ["web/package.json", "web/package-lock.json"]
        def bump(title, body=""):
            return lanes.merge_refusal(pr(files, author="app/dependabot", title=title, body=body), CONFIG)
        self.assertIn("6.1", bump("chore(deps): bump lints from 5.1.1 to 6.1.0 in /libs/music"))
        self.assertIn("0.4", bump("Bump left-pad from 0.3.2 to 0.4.0"))
        self.assertIsNone(bump("chore(deps): bump lints from 5.1.1 to 5.2.0"))
        self.assertIsNone(bump("Bump left-pad from 0.3.2 to 0.3.9"))
        grouped = "Bumps the npm-minor group with 2 updates.\nUpdates `next` from 15.1.0 to 16.0.1\nUpdates `react` from 19.1.0 to 19.2.0"
        self.assertIn("15.1 → 16.0", bump("chore(deps): bump the npm-minor group", grouped))
        notes = "Updates `react` from 19.1.0 to 19.2.0\n\n## Release notes\nMigrated from 1.0 to 2.0 internally"
        self.assertIsNone(bump("chore(deps): bump the npm-minor group", notes))

    def test_approved_chores_merge_now_update_or_queue(self) -> None:
        self.assertEqual(lanes.merge_step("CLEAN"), "merge")
        self.assertEqual(lanes.merge_step("HAS_HOOKS"), "merge")
        self.assertEqual(lanes.merge_step("BEHIND"), "update")
        for state in ("BLOCKED", "UNSTABLE", "UNKNOWN", "DIRTY"):
            self.assertEqual(lanes.merge_step(state), "queue", state)

    def test_owner_prs_are_not_read_as_version_bumps(self) -> None:
        self.assertIsNone(lanes.merge_refusal(pr(["docs/a.md"], title="docs: move from 1.0 to 2.0 terms"), CONFIG))

    def test_product_automation_and_instructions_wait_for_the_owner(self) -> None:
        for path in ["src/main.py", ".github/workflows/ci.yml", ".github/README.md", "AGENTS.md",
                     ".agents/skills/x/SKILL.md", ".vscode/settings.json", "tools/gate.py",
                     "infra/README.md", "justfile"]:
            with self.subTest(path=path):
                self.assertIsNotNone(lanes.merge_refusal(pr([path]), CONFIG))

    def test_drafts_forks_strangers_and_truncated_lists_wait(self) -> None:
        for candidate in [pr(["docs/a.md"], isDraft=True), pr(["docs/a.md"], baseRefName="release"),
                          pr(["docs/a.md"], headRepositoryOwner={"login": "fork"}),
                          pr(["docs/a.md"], author="someone"),
                          pr([f"docs/{i}.md" for i in range(100)]), pr([])]:
            self.assertIsNotNone(lanes.merge_refusal(candidate, CONFIG))


    def test_renames_wait_because_the_old_path_is_hidden(self) -> None:
        moved = pr(["docs/release.yml"])
        moved["files"][0]["changeType"] = "RENAMED"
        self.assertIn("renames", lanes.merge_refusal(moved, CONFIG))
        unknown = pr(["docs/release.yml"])
        del unknown["files"][0]["changeType"]
        self.assertIn("renames", lanes.merge_refusal(unknown, CONFIG))

    def test_unresolved_review_threads_wait_for_their_answer(self) -> None:
        self.assertIn("1 unresolved review thread", lanes.merge_refusal(pr(["docs/a.md"], unresolvedThreads=[thread()]), CONFIG))
        self.assertIsNone(lanes.merge_refusal(pr(["docs/a.md"], unresolvedThreads=[]), CONFIG))

    def test_a_pr_labelled_for_the_owner_waits_for_the_owner(self) -> None:
        lesson = pr(["docs/a.md"], labels=[{"name": "review:owner"}])
        self.assertEqual(lanes.merge_refusal(lesson, CONFIG), "for the owner: labelled review:owner")


def sized(*files):
    """A PR whose files carry (path, additions, deletions)."""
    candidate = pr([])
    candidate["files"] = [{"path": f, "changeType": "MODIFIED", "additions": a, "deletions": d}
                          for f, a, d in files]
    return candidate


class TriageTests(unittest.TestCase):
    CFG = config(agentReview=True, ownerPaths=["/firestore/"], ownerLabels=["release:beta"], ownerLines=50)
    SCOPE = ["src/stage/"]

    def triage(self, candidate, scope=SCOPE):
        return lanes.triage(candidate, self.CFG, scope)

    def test_every_owner_rule_names_itself(self) -> None:
        moved = pr(["src/stage/a.py"])
        moved["files"][0]["changeType"] = "RENAMED"
        dependabot = pr(["web/package.json"], author="app/dependabot", title="Bump x from 1.2.0 to 2.0.0")
        cases = [
            (pr(["src/stage/a.py"], labels=[{"name": "review:owner"}]), self.SCOPE, "labelled review:owner"),
            (pr(["src/stage/a.py"], author="someone"), self.SCOPE, "neither the owner"),
            (pr([]), self.SCOPE, "empty or truncated"),
            (moved, self.SCOPE, "renames"),
            (pr(["AGENTS.md"]), self.SCOPE, "owner paths: AGENTS.md"),
            (pr(["src/data/firestore/codec.py"]), ["src/"], "owner paths"),
            (pr(["src/stage/a.py"], labels=[{"name": "release:beta"}]), self.SCOPE, "ships on merge: release:beta"),
            (dependabot, None, "major version"),
            (sized(("src/stage/a.py", 40, 11)), self.SCOPE, "51 changed lines"),
            (pr(["src/stage/a.py"]), None, "closes no issue with a scope packet"),
            (pr(["src/kernel/b.py"]), self.SCOPE, "outside its issue's scope packet: src/kernel/b.py"),
        ]
        for candidate, scope, rule in cases:
            with self.subTest(rule=rule):
                kind, why = self.triage(candidate, scope)
                self.assertEqual(kind, "owner")
                self.assertIn(rule, why)

    def test_a_pr_matching_no_owner_rule_lands_without_the_owner(self) -> None:
        self.assertEqual(self.triage(pr(["docs/guide.md", "tests/stage/test_a.py"]), None)[0], "chore")
        self.assertEqual(self.triage(pr(["src/stage/a.py", "tests/stage/test_a.py"]))[0], "reviewed")
        self.assertEqual(self.triage(sized(("src/stage/a.py", 30, 20)))[0], "reviewed")

    def test_docs_and_tests_count_toward_neither_size_nor_scope(self) -> None:
        self.assertEqual(self.triage(sized(("docs/huge.md", 900, 0), ("src/stage/a.py", 5, 0)))[0], "reviewed")


class QueueTests(unittest.TestCase):
    def test_only_afk_claims_hold_the_one_at_a_time_queue(self) -> None:
        issues = [issue(3, ("lane:owner", "state:started")), issue(4, ("lane:afk",))]
        self.assertEqual(lanes.afk_in_flight(issues, set()), [])
        issues.append(issue(5, ("lane:afk", "state:claimed")))
        self.assertEqual([i["number"] for i in lanes.afk_in_flight(issues, set())], [5])
        self.assertEqual(lanes.afk_in_flight(issues, {5}), [])


SHA = "a" * 40


def reviewed_pr(files=("src/stage/a.py",), verdict="ready", sha=SHA, **overrides):
    marker = f"<!-- agent-review sha={SHA} round=1 verdict={verdict} -->\nReady to merge."
    fields = {"headRefName": "agent/afk-7-thing", "headRefOid": sha, "labels": [], "comments": [],
              "reviews": [{"author": {"login": OWNER}, "state": "COMMENTED", "body": marker,
                           "submittedAt": "2026-10-02T10:00:00Z"}]}
    return pr(list(files), **{**fields, **overrides})


class ReviewedMergeTests(unittest.TestCase):
    AGENT = config(agentReview=True)

    def refusal(self, candidate, cfg=None):
        return lanes.merge_refusal(candidate, cfg or self.AGENT, ["src/stage/"])

    def test_a_ready_review_at_the_head_merges(self) -> None:
        self.assertIsNone(self.refusal(reviewed_pr()))

    def test_without_an_agent_review_it_merges_on_green(self) -> None:
        self.assertIsNone(self.refusal(reviewed_pr(reviews=[])))
        self.assertIsNone(self.refusal(reviewed_pr(reviews=[]), CONFIG))

    def test_an_agent_review_at_the_head_that_finds_problems_holds_it(self) -> None:
        for verdict in ("fixes", "owner", "rounds"):
            self.assertIn(f"says {verdict}", self.refusal(reviewed_pr(verdict=verdict)), verdict)

    def test_commits_after_a_holding_review_lift_it(self) -> None:
        self.assertIsNone(self.refusal(reviewed_pr(verdict="fixes", sha="b" * 40)))

    def test_only_the_reviewer_account_can_hold_it(self) -> None:
        stranger = reviewed_pr(verdict="fixes")
        stranger["reviews"][0]["author"] = {"login": "stranger"}
        self.assertIsNone(self.refusal(stranger))

    def test_pending_reviews_without_a_time_are_ignored(self) -> None:
        pending = {"author": {"login": OWNER}, "state": "PENDING", "body": "", "submittedAt": None}
        ready = reviewed_pr()
        self.assertIsNone(self.refusal({**ready, "reviews": ready["reviews"] + [pending]}))

    def test_the_newest_agent_review_decides(self) -> None:
        older = {"author": {"login": OWNER}, "state": "COMMENTED", "submittedAt": "2026-10-02T09:00:00Z",
                 "body": f"<!-- agent-review sha={SHA} round=1 verdict=ready -->"}
        newer = {"author": {"login": OWNER}, "state": "COMMENTED", "submittedAt": "2026-10-02T11:00:00Z",
                 "body": f"<!-- agent-review sha={SHA} round=2 verdict=fixes -->"}
        self.assertIn("says fixes", self.refusal(reviewed_pr(reviews=[older, newer])))
        later_ready = {**older, "submittedAt": "2026-10-02T12:00:00Z"}
        self.assertIsNone(self.refusal(reviewed_pr(reviews=[newer, later_ready])))

    def test_any_branch_merges_and_owner_rules_hand_over(self) -> None:
        self.assertIsNone(self.refusal(reviewed_pr(headRefName="feature/12-thing")))
        self.assertIn("owner paths", self.refusal(reviewed_pr(files=["infra/dns.tf"])))
        self.assertIn("review:owner", self.refusal(reviewed_pr(labels=[{"name": "review:owner"}])))
        self.assertIn("open, ready", self.refusal(reviewed_pr(isDraft=True)))

    def test_people_after_the_review_hold_the_merge(self) -> None:
        later = "2026-10-02T12:00:00Z"
        person = [{"author": {"login": OWNER}, "body": "Wait, check the iPad.", "createdAt": later}]
        bot = [{"author": {"login": OWNER}, "body": "Ok\n\n_Generated by an agent_", "createdAt": later}]
        self.assertIn("person", self.refusal(reviewed_pr(comments=person)))
        self.assertIsNone(self.refusal(reviewed_pr(comments=bot)))
        quoted = [{"author": {"login": OWNER}, "createdAt": later,
                   "body": "Generated by a bot? No: hold this.\n\n_Generated by an agent_ said earlier."}]
        self.assertIn("person", self.refusal(reviewed_pr(comments=quoted)))
        blocked = {"author": {"login": "reviewer"}, "state": "CHANGES_REQUESTED", "body": "No.",
                   "submittedAt": "2026-10-02T08:00:00Z"}
        ready = reviewed_pr()
        self.assertIn("requests changes", self.refusal({**ready, "reviews": ready["reviews"] + [blocked]}))
        comment = {"author": {"login": "reviewer"}, "state": "COMMENTED", "body": "One more thought.",
                   "submittedAt": "2026-10-02T09:00:00Z"}
        still = {**ready, "reviews": [blocked, comment] + ready["reviews"]}
        self.assertIn("requests changes", self.refusal(still))
        dismissed = {**blocked, "state": "DISMISSED", "submittedAt": "2026-10-02T09:30:00Z"}
        self.assertIsNone(self.refusal({**ready, "reviews": [blocked, dismissed] + ready["reviews"]}))

    def test_unresolved_review_threads_hold_the_merge(self) -> None:
        self.assertIn("2 unresolved review threads", self.refusal(reviewed_pr(unresolvedThreads=[thread(), thread()])))
        self.assertIsNone(self.refusal(reviewed_pr(unresolvedThreads=[])))

    def test_renames_wait_for_the_owner(self) -> None:
        moved = reviewed_pr()
        moved["files"][0]["changeType"] = "RENAMED"
        self.assertIn("renames", self.refusal(moved))


    def test_reviews_count_in_time_order(self) -> None:
        blocked = {"author": {"login": "reviewer"}, "state": "CHANGES_REQUESTED", "body": "No.",
                   "submittedAt": "2026-10-02T08:00:00Z"}
        approved = {**blocked, "state": "APPROVED", "submittedAt": "2026-10-02T09:00:00Z"}
        ready = reviewed_pr()
        self.assertIsNone(self.refusal({**ready, "reviews": [approved, blocked] + ready["reviews"]}))


def check(name, status="COMPLETED", conclusion="SUCCESS"):
    return {"__typename": "CheckRun", "name": name, "status": status, "conclusion": conclusion}


def mergeable_pr(**overrides):
    return {"number": 7, "state": "OPEN", "isDraft": False, "baseRefName": "main", "mergeable": "MERGEABLE",
            "mergeStateStatus": "CLEAN", "statusCheckRollup": [check("unit")], "reviews": [],
            "unresolvedThreads": [], **overrides}


class BlockersTests(unittest.TestCase):
    """What an attended session reads before it calls a PR ready, hands it over or merges it."""

    def test_a_green_up_to_date_pr_with_no_open_threads_has_none(self) -> None:
        self.assertEqual(lanes.blockers(mergeable_pr()), [])

    def test_failing_and_pending_checks_are_named(self) -> None:
        found = lanes.blockers(mergeable_pr(mergeStateStatus="BLOCKED", statusCheckRollup=[
            check("unit", conclusion="FAILURE"), check("lint", status="IN_PROGRESS", conclusion=None),
            check("docs", conclusion="SKIPPED"),
            {"__typename": "StatusContext", "context": "ci/legacy", "state": "ERROR"},
            {"__typename": "StatusContext", "context": "ci/deploy", "state": "PENDING"}]))
        self.assertEqual(found, ["check failing: unit", "check failing: ci/legacy",
                                 "check pending: lint", "check pending: ci/deploy"])

    def test_a_conflict_or_a_branch_behind_the_base_is_named(self) -> None:
        self.assertEqual(lanes.blockers(mergeable_pr(mergeable="CONFLICTING", mergeStateStatus="DIRTY")),
                         ["conflicts with main: merge origin/main and resolve"])
        self.assertEqual(lanes.blockers(mergeable_pr(mergeStateStatus="BEHIND")),
                         ["behind main: update the branch"])
        self.assertEqual(lanes.blockers(mergeable_pr(mergeable="UNKNOWN", mergeStateStatus="UNKNOWN")),
                         ["mergeability not computed yet: run again"])

    def test_each_unresolved_thread_names_its_place_first_line_and_writer(self) -> None:
        found = lanes.blockers(mergeable_pr(mergeStateStatus="BLOCKED", unresolvedThreads=[
            thread(), thread(path="README.md", line=None, body="Why this word?\nMore.", author="alice")]))
        self.assertEqual(found, ["2 unresolved review threads: answer, then resolve each",
                                 "  src/a.py:3 (agent-written): Guard the empty list.",
                                 "  README.md (@alice): Why this word?"])

    def test_a_standing_change_request_is_named(self) -> None:
        reviews = [{"author": {"login": "alice"}, "state": "CHANGES_REQUESTED", "submittedAt": "2026-10-01T10:00:00Z"},
                   {"author": {"login": "bob"}, "state": "CHANGES_REQUESTED", "submittedAt": "2026-10-01T10:00:00Z"},
                   {"author": {"login": "bob"}, "state": "APPROVED", "submittedAt": "2026-10-02T10:00:00Z"}]
        self.assertEqual(lanes.blockers(mergeable_pr(mergeStateStatus="BLOCKED", reviews=reviews)),
                         ["changes requested by @alice"])

    def test_drafts_closed_prs_and_unexplained_blocks_are_named(self) -> None:
        self.assertEqual(lanes.blockers(mergeable_pr(isDraft=True, mergeStateStatus="DRAFT")),
                         ["draft: mark it ready for review"])
        self.assertEqual(lanes.blockers(mergeable_pr(state="MERGED")), ["not open: MERGED"])
        self.assertEqual(lanes.blockers(mergeable_pr(mergeStateStatus="BLOCKED")),
                         ["blocked by a rule of the base branch this command does not read (a required review?)"])


class BaseBranchTests(unittest.TestCase):
    """Runs read the remote base branch and never depend on the owner's checkout."""

    def git(self, cwd, *args):
        subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True, text=True)

    def test_queue_reads_origin_main_while_the_checkout_holds_other_work(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            origin, seed, owner = (Path(tmp) / n for n in ("origin.git", "seed", "owner"))
            ident = ["-c", "user.name=t", "-c", "user.email=t@t"]
            self.git(tmp, "init", "--quiet", "--bare", "-b", "main", str(origin))
            self.git(tmp, "clone", "--quiet", str(origin), str(seed))
            (seed / ".github").mkdir()
            (seed / ".github/lanes.json").write_text(json.dumps(
                {"repo": f"{OWNER}/app", "protected": ["^infra/"]}))
            (seed / "app.py").write_text("main\n")
            self.git(seed, "add", ".")
            self.git(seed, *ident, "commit", "--quiet", "-m", "base")
            self.git(seed, "push", "--quiet", "origin", "HEAD:main")
            self.git(tmp, "clone", "--quiet", str(origin), str(owner))
            # The owner works on a branch with its own config and uncommitted edits.
            self.git(owner, "checkout", "--quiet", "-b", "owner-work")
            (owner / ".github/lanes.json").write_text(json.dumps(
                {"repo": f"{OWNER}/app", "protected": ["^old/"]}))
            (owner / "app.py").write_text("conflicting edit\n")
            (owner / "draft.py").write_text("untracked\n")
            # Main moves on after the owner's clone.
            (seed / "infra").mkdir()
            (seed / "infra/dns.tf").write_text("dns\n")
            self.git(seed, "add", ".")
            self.git(seed, *ident, "commit", "--quiet", "-m", "infra")
            self.git(seed, "push", "--quiet", "origin", "HEAD:main")
            here = os.getcwd()
            os.chdir(owner)
            try:
                repo = lanes.Repo()
            finally:
                os.chdir(here)
            self.assertIn("^infra/", repo.config["protected"])
            self.assertNotIn("^old/", repo.config["protected"])
            self.assertIn("infra/dns.tf", repo.tracked())
            self.assertNotIn("draft.py", repo.tracked())
            self.assertEqual((owner / "app.py").read_text(), "conflicting edit\n")
            branch = subprocess.run(["git", "branch", "--show-current"], cwd=owner,
                                    capture_output=True, text=True, check=True).stdout.strip()
            self.assertEqual(branch, "owner-work")

    def test_a_move_lists_its_old_path_too(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            ident = ["-c", "user.name=t", "-c", "user.email=t@t"]
            self.git(tmp, "init", "--quiet", "-b", "main")
            (Path(tmp) / "infra").mkdir()
            (Path(tmp) / "infra/dns.tf").write_text("dns\n" * 20)
            self.git(tmp, "add", ".")
            self.git(tmp, *ident, "commit", "--quiet", "-m", "base")
            self.git(tmp, "mv", "infra/dns.tf", "dns.tf")
            self.assertEqual(lanes.changed_files(tmp, "main"), ["dns.tf", "infra/dns.tf"])
            (Path(tmp) / "a b.md").write_text("spaced\n")
            self.assertIn("a b.md", lanes.changed_files(tmp, "main"))


if __name__ == "__main__":
    unittest.main()
