"""The post-push hook: a session reads its PR's open review threads after every push."""

from __future__ import annotations

import importlib.util
import io
import json
import subprocess
import sys
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "plugins/common/workflow/skills/afk/scripts"
sys.path.insert(0, str(SCRIPTS))
spec = importlib.util.spec_from_file_location("pushed", SCRIPTS / "pushed.py")
pushed = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pushed)

THREAD = {"path": "lib/a.dart", "line": 7, "outdated": False, "author": "owner",
          "body": "**Blocking:** a landscape phone gets the bar.\n\n_Generated by Host_"}


def branches(text, current="feat/here"):
    with mock.patch.object(pushed.guard, "current_branch", return_value=current) as head:
        return pushed.pushed_branches(text, "/wt"), head


class PushedBranchesTests(unittest.TestCase):
    def test_a_bare_push_names_the_branch_checked_out(self) -> None:
        found, head = branches("git push")
        self.assertEqual(found, ["feat/here"])
        head.assert_called_once_with("/wt")

    def test_a_refspec_names_the_remote_branch(self) -> None:
        self.assertEqual(branches("git push origin local:feat/remote")[0], ["feat/remote"])

    def test_options_and_a_forced_refspec_name_the_branch(self) -> None:
        text = "git push --force-with-lease -u origin +refs/heads/feat/x"
        self.assertEqual(branches(text)[0], ["feat/x"])

    def test_a_push_after_other_commands_counts(self) -> None:
        self.assertEqual(branches("just verify && git push origin feat/y")[0], ["feat/y"])

    def test_head_in_another_checkout_reads_that_checkout(self) -> None:
        found, head = branches("git -C ../other push origin HEAD")
        self.assertEqual(found, ["feat/here"])
        head.assert_called_once_with("/wt/../other")

    def test_text_that_only_mentions_a_push_pushes_nothing(self) -> None:
        self.assertEqual(branches("echo 'git push origin feat/z'")[0], [])

    def test_deleting_a_branch_or_pushing_tags_names_no_pr(self) -> None:
        self.assertEqual(branches("git push origin --delete feat/old")[0], [])
        self.assertEqual(branches("git push --tags")[0], [])

    def test_a_line_the_parser_cannot_read_names_nothing(self) -> None:
        self.assertEqual(branches("git push origin 'feat/unclosed")[0], [])


def gh_view(state="OPEN", reviews=()):
    out = json.dumps({"url": "https://github.com/o/r/pull/9", "state": state, "reviews": list(reviews)})
    return subprocess.CompletedProcess([], 0, stdout=out, stderr="")


class OpenReviewTests(unittest.TestCase):
    def test_an_open_pr_names_each_thread_and_change_request(self) -> None:
        change = {"author": {"login": "owner"}, "state": "CHANGES_REQUESTED", "submittedAt": "2026-10-06T22:00:00Z"}
        with mock.patch.object(pushed.subprocess, "run", return_value=gh_view(reviews=[change])), \
                mock.patch.object(pushed.lanes, "unresolved_threads", return_value=[THREAD]) as threads:
            url, lines = pushed.open_review("feat/x", "/wt")
        threads.assert_called_once_with("o/r", "9")
        self.assertEqual(url, "https://github.com/o/r/pull/9")
        self.assertEqual(lines, ["1 unresolved review thread: answer, then resolve each",
                                 "  lib/a.dart:7 (agent-written): **Blocking:** a landscape phone gets the bar.",
                                 "changes requested by @owner"])

    def test_a_pr_with_nothing_open_says_nothing(self) -> None:
        with mock.patch.object(pushed.subprocess, "run", return_value=gh_view()), \
                mock.patch.object(pushed.lanes, "unresolved_threads", return_value=[]):
            self.assertIsNone(pushed.open_review("feat/x", "/wt"))

    def test_a_merged_pr_or_a_branch_without_one_says_nothing(self) -> None:
        with mock.patch.object(pushed.subprocess, "run", return_value=gh_view(state="MERGED")):
            self.assertIsNone(pushed.open_review("feat/x", "/wt"))
        missing = subprocess.CalledProcessError(1, "gh", stderr="no pull requests found")
        with mock.patch.object(pushed.subprocess, "run", side_effect=missing):
            self.assertIsNone(pushed.open_review("feat/x", "/wt"))


class HookTests(unittest.TestCase):
    def run_hook(self, event, held=("https://github.com/o/r/pull/9", ["1 unresolved review thread"])):
        out = io.StringIO()
        with mock.patch.object(pushed, "pushed_branches", return_value=["feat/x"]) as found, \
                mock.patch.object(pushed, "open_review", return_value=held), redirect_stdout(out):
            pushed.main(event)
        return out.getvalue(), found

    def test_a_push_with_open_threads_adds_them_to_the_context(self) -> None:
        printed, _ = self.run_hook({"tool_name": "Bash", "tool_input": {"command": "git push"}, "cwd": "/wt"})
        output = json.loads(printed)["hookSpecificOutput"]
        self.assertEqual(output["hookEventName"], "PostToolUse")
        self.assertIn("https://github.com/o/r/pull/9 still has review items open", output["additionalContext"])
        self.assertIn("Merge gate", output["additionalContext"])
        self.assertIn("1 unresolved review thread", output["additionalContext"])

    def test_a_push_with_nothing_open_prints_nothing(self) -> None:
        printed, _ = self.run_hook({"tool_name": "Bash", "tool_input": {"command": "git push"}}, held=None)
        self.assertEqual(printed, "")

    def test_calls_that_push_nothing_ask_nothing(self) -> None:
        for event in ({"tool_name": "Edit", "tool_input": {"file_path": "push.md"}},
                      {"tool_name": "Bash", "tool_input": {"command": "git status"}}):
            printed, found = self.run_hook(event)
            self.assertEqual(printed, "")
            found.assert_not_called()

    def test_plugin_runs_the_hook_after_every_shell_command(self) -> None:
        package = ROOT / "plugins/common/workflow"
        manifest = json.loads((package / ".claude-plugin/plugin.json").read_text())
        hooks = json.loads((package / manifest["hooks"]).read_text())
        entry = hooks["hooks"]["PostToolUse"][0]
        self.assertRegex("Bash", entry["matcher"])
        self.assertIn("skills/afk/scripts/pushed.py", entry["hooks"][0]["command"])


if __name__ == "__main__":
    unittest.main()
